<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.8.6">
]
>

<object class="weka.classifiers.sklearn.ScikitLearnClassifier" name="__root__" version="3.8.6">
   <object class="boolean" name="debug" primitive="yes">false</object>
   <object array="yes" class="java.lang.String" name="options">
      <object class="java.lang.String" name="0">-batch</object>
      <object class="java.lang.String" name="1">100</object>
      <object class="java.lang.String" name="2">-learner</object>
      <object class="java.lang.String" name="3">XGBClassifier</object>
      <object class="java.lang.String" name="4">-parameters</object>
      <object class="java.lang.String" name="5">gamma=1,subsample=0.5,colsample_bynode=0.5,tree_method=&quot;exact&quot;,max_depth=6</object>
      <object class="java.lang.String" name="6">-py-command</object>
      <object class="java.lang.String" name="7">python</object>
      <object class="java.lang.String" name="8">-py-path</object>
      <object class="java.lang.String" name="9">default</object>
      <object class="java.lang.String" name="10">-server-name</object>
      <object class="java.lang.String" name="11">none</object>
   </object>
</object>
